# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [1]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [3]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidim = np.array([1,2,3,4,5])
# O un array de dos dimensiones (bidimensional)
array_bidim = np.array([[1,2,3],
                       [4,5,6]])
# O un array de tres dimensiones (tridimensional)
array_tridim = np.array([[[1,2,3],
                          [4,5,6],
                          [7,8,9],
                          [10,11,12]]])

Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [4]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [5]:
# Atributos del array bidimensional
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Atributos del array tridimensional
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((1, 4, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [9]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd

datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

In [10]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
cero = np.zeros((2,4,3))
cero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0,101,5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [15]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0,10,(2,5))
array_2

array([[2, 8, 4, 8, 1],
       [4, 6, 2, 0, 4]])

In [17]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3,5))
array_3

array([[0.98905511, 0.04509917, 0.64661703, 0.0395524 , 0.40700966],
       [0.48930439, 0.56174023, 0.2535924 , 0.90474492, 0.25996361],
       [0.87430589, 0.67248564, 0.84066284, 0.12029473, 0.300859  ]])

In [19]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(27)
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0, 10, (3,5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [20]:
# Encontramos los valores únicos del array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [21]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [22]:
# Extraemos las primeras dos filas del array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [23]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [24]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0,10,(3,4))
array_6 = np.ones((3,4))

In [25]:
# invocamos el array_5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [26]:
# invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
# Sumamos los dos arrays
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [28]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4,3))

In [29]:
# Intentaremos sumar los arrays 6 y 7
array_6 + array_7

ValueError: ignored

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [30]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4,3))

In [31]:
# Restamos el array_8 al array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1,5,(3,3))
array_10 = np.random.randint(1,5,(3,3))

In [38]:
# invocamos el array_9
array_9

array([[4, 1, 1],
       [1, 2, 2],
       [1, 1, 4]])

In [39]:
# invocamos el array_10
array_10

array([[1, 4, 1],
       [2, 4, 2],
       [3, 3, 1]])

In [40]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10

array([[4, 4, 1],
       [2, 8, 4],
       [3, 3, 4]])

In [41]:
# Elevamos el array_9 al cuadrado
array_9**2

array([[16,  1,  1],
       [ 1,  4,  4],
       [ 1,  1, 16]])

In [42]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[1.        , 2.        , 1.        ],
       [1.41421356, 2.        , 1.41421356],
       [1.73205081, 1.73205081, 1.        ]])

In [43]:
# Hallamos el promedio de los valores del array_9
array_9.mean()

1.8888888888888888

In [44]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

4

In [45]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

1

In [46]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9,1))

In [47]:
# invocamos el array_11
array_11

array([[4],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [4]])

In [48]:
# Transponemos el array_11
array_11.T

array([[4, 1, 1, 1, 2, 2, 1, 1, 4]])

In [49]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12

array([[ True, False, False],
       [False, False, False],
       [False, False,  True]])

¿Qué tipos de datos forman parte del array de resultados?

In [50]:
# Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [51]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[False, False,  True],
       [False, False,  True],
       [False, False, False]])

In [52]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10

array([[ True, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [53]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[ True, False, False],
       [False, False, False],
       [False, False,  True]])

In [54]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)

array([[1, 1, 4],
       [1, 2, 2],
       [1, 1, 4]])